# Build settings
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
plugins:
  - jekyll-default-layout
title: Modding guide
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  This guide is intended to give complete beginners a taste of how
  to go about creating mods for the Subnautica and Below Zero games. 
  You'll learn everything from what software you require, how to install it 
  and the basics of modding the Subnautica games. 
  Within the guide you'll write you own mod, step by step, to set you up to build your own, bigger and better, mods.
baseurl: "/Subnautica" # the subpath of your site, e.g. /blog
url: "https://mroshaw.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  mroshaw

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
